package com.pluralsight.dynamodb.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.pluralsight.dynamodb.LocalDateTimeConverter

import java.time.LocalDateTime

@DynamoDBTable(tableName = "Comments")
class Comment {
    @DynamoDBHashKey
    var itemId: String? = null

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    var messageId: String? = null

    @DynamoDBAttribute
    var message: String? = null

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter::class)
    var dateTime: LocalDateTime? = null

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserID-index")
    var userId: String? = null

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "UserID-index", localSecondaryIndexName = "Rating-index")
    var rating: Int = 0

    override fun toString(): String {
        return "Comment{" +
                "itemId='" + itemId + '\''.toString() +
                ", messageId='" + messageId + '\''.toString() +
                ", message='" + message + '\''.toString() +
                ", dateTime='" + dateTime + '\''.toString() +
                ", userId='" + userId + '\''.toString() +
                ", rating=" + rating +
                '}'.toString()
    }
}
