package com.pluralsight.dynamodb.domain

import com.amazonaws.services.dynamodbv2.datamodeling.*

@DynamoDBTable(tableName = "Items")
class Item {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    var id: String? = null

    @DynamoDBAttribute
    var name: String? = null

    @DynamoDBAttribute
    var description: String? = null

    @DynamoDBAttribute
    var totalRating: Int = 0

    @DynamoDBAttribute
    var totalComments: Int = 0

    @DynamoDBVersionAttribute
    var version: Long? = null

    val rating: Double
        @DynamoDBIgnore
        get() = totalRating.toDouble() / totalComments

    override fun toString(): String {
        return "Item{" +
                "id='" + id + '\''.toString() +
                ", name='" + name + '\''.toString() +
                ", description='" + description + '\''.toString() +
                ", rating=" + rating +
                '}'.toString()
    }
}
